object Versions {
    val kotlinVersion = "1.6.10"
    val gradleVersion = "7.0.4"
    val appcompatVersion = "1.4.1"
    val junitVersion = "4.12"
    val androidxTestRunnerVersion = "1.4.0"
    val espressoCoreVersion = "3.4.0"
    val daggerVersion = "2.40"
    val retrofitVersion = "2.9.0"
    val okhttpVersion = "4.9.1"
    val recyclerViewVersion = "1.2.1"
    val rxAndroidVersion = "3.0.0"
    val rxJavaVersion = "3.1.3"
    val glideVersion = "4.12.0"
    val truthExtVersion = "1.3.0"
    val mockKVersion = "1.12.1"
    val coreTestingVersion = "2.0.0"
    val materialVersion = "1.5.0"
    val gradleVersionPluginVersion = "0.27.0"
    val constraintLayout = "2.1.3"
}